services:
  - type: web
    name: ivy-homes-assignment
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: IVY_BASE_URL
        value: https://solve.ivy.homes
      - key: IVY_API_KEY
        sync: false
      - key: IVY_CITY
        value: Bangalore
      - key: IVY_ASSIGNED_LOCALITY
        value: Yelahanka
      - key: IVY_DEMO_PASSWORD
        value: 5edd65b804
      - key: PYTHON_VERSION
        value: "3.11.0"
